spring.config.import: "configserver:"

spring:
  application.name: service-discovery
  cloud.config:
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 20
    uri: http://centralised-config:8888

logging:
  level:
    root: INFO

