spring.config.import: "configserver:"

spring:
  application.name: user-service
  cloud.config:
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 20
    uri: http://localhost:8888

logging:
  level:
    root: INFO

---
spring.config.activate.on-profile: docker

spring.cloud.config.uri: http://centralised-config:8888
